# Generated by Django 6.0.6 on 2026-06-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20)),
                ('application_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_priority', models.PositiveSmallIntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.student')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('reserved_seats', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='allocation.course')),
            ],
            options={
                'unique_together': {('course', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='allocation.student')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('student', 'priority')},
            },
        ),
    ]
