# Generated by Django 6.0.6 on 2026-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_rejectedallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application_date',
            field=models.DateField(),
        ),
    ]
