# Generated by Django 6.0.6 on 2026-06-11 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_alter_student_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedallocation',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rejectedallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.student'),
        ),
    ]
